In [11]:
# task1
import random
import numpy as np

vector1=np.arange(10,49,1)



In [12]:
# task2

matrix1=np.arange(0,9).reshape(3,3)
print(matrix1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# task3
l1=[[1 if j==i else 0 for j in range(3)] for i in range(3)]
matrix2=np.array(l1)
print(l1)

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]


In [20]:
# task4
l2=[[[random.randint(0,9) for j in range(3)] for i in range(3)] for k in range(3)]
matrix3=np.array(l2)
print(matrix3)


[[[9 0 2]
  [3 0 2]
  [6 4 2]]

 [[7 0 8]
  [2 9 0]
  [5 7 9]]

 [[8 9 4]
  [1 4 1]
  [1 1 1]]]


In [23]:
# task5
l3=[[random.randint(1,1000) for j in range(10)] for i in range(10)]
matrix4=np.array(l3)
maxval1=np.max(matrix4)
print(maxval1)

961


In [27]:
# task6
vector2=np.array(np.random.randint(1,1000,30) )
mean_value=np.mean(vector2)
print(mean_value)

557.0666666666667


In [ ]:
# task7
rand5x5=np.random.randint(1,1000,(5,5))
matrix_min = rand5x5.min()
matrix_max = rand5x5.max()
normalized_matrix = (rand5x5 - matrix_min) / (matrix_max - matrix_min)

normalized_matrix

array([[0.97055731, 0.94847529, 0.06729758, 0.        , 0.09148265],
       [0.4595163 , 0.66982124, 0.96004206, 0.04416404, 1.        ],
       [0.93059937, 0.51314406, 0.33964248, 0.70031546, 0.8338591 ],
       [0.66246057, 0.27970557, 0.02839117, 0.13038906, 0.25341746],
       [0.13459516, 0.86014721, 0.3491062 , 0.90325973, 0.49737119]])