In [11]:
# task1
import random
import numpy as np

vector1=np.arange(10,49,1)



In [12]:
# task2

matrix1=np.arange(0,9).reshape(3,3)
print(matrix1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# task3
l1=[[1 if j==i else 0 for j in range(3)] for i in range(3)]
matrix2=np.array(l1)
print(l1)

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]


In [20]:
# task4
l2=[[[random.randint(0,9) for j in range(3)] for i in range(3)] for k in range(3)]
matrix3=np.array(l2)
print(matrix3)


[[[9 0 2]
  [3 0 2]
  [6 4 2]]

 [[7 0 8]
  [2 9 0]
  [5 7 9]]

 [[8 9 4]
  [1 4 1]
  [1 1 1]]]


In [23]:
# task5
l3=[[random.randint(1,1000) for j in range(10)] for i in range(10)]
matrix4=np.array(l3)
maxval1=np.max(matrix4)
print(maxval1)

961


In [27]:
# task6
vector2=np.array(np.random.randint(1,1000,30) )
mean_value=np.mean(vector2)
print(mean_value)

557.0666666666667


In [ ]:
# task7
rand5x5=np.random.randint(1,1000,(5,5))
matrix_min = rand5x5.min()
matrix_max = rand5x5.max()
normalized_matrix = (rand5x5 - matrix_min) / (matrix_max - matrix_min)

normalized_matrix

array([[0.97055731, 0.94847529, 0.06729758, 0.        , 0.09148265],
       [0.4595163 , 0.66982124, 0.96004206, 0.04416404, 1.        ],
       [0.93059937, 0.51314406, 0.33964248, 0.70031546, 0.8338591 ],
       [0.66246057, 0.27970557, 0.02839117, 0.13038906, 0.25341746],
       [0.13459516, 0.86014721, 0.3491062 , 0.90325973, 0.49737119]])

In [31]:
# task8
matrix5=np.random.randint(1,1000,(5,3))
matrix6=np.random.randint(1,1000,(3,2))
product_matrix = np.dot(matrix5, matrix6)
print(product_matrix)

[[ 582414  924147]
 [ 347673  749572]
 [ 598221 1385201]
 [ 322656  587236]
 [ 838134 1462171]]


In [32]:
# task9
matrix3=np.random.randint(1,1000,(3,3))
matrix4=np.random.randint(1,1000,(3,3))
product= np.dot(matrix3, matrix4)
print(product)

[[1454845  859764  286416]
 [ 724065  246488  148062]
 [ 995790  491854  282246]]


In [33]:
# task10
matrix7=np.random.randint(1,1000,(4,4))
transpose = np.transpose(matrix7)
print(transpose)

[[882 181 681 809]
 [551 743 975 963]
 [190  19 562 226]
 [487 743 765 936]]


In [36]:
# task11
matrix8=np.random.randint(1,1000,(3,3))
det= np.linalg.det(matrix8)
print(det)

114750434.99999984


In [37]:
# task12
matrixA=np.random.randint(1,1000,(3,4))
matrixB=np.random.randint(1,1000,(4,3))
matrixC=np.dot(matrixA,matrixB)
print(matrixC)

[[1078757 1405519 1016596]
 [1141322 1294552  632357]
 [ 912739  891077  596973]]


In [40]:
# task13
matrix9=np.random.randint(1,1000,(3,3))
matrix10=np.random.randint(1,1000,(3,1))
matrix11=np.dot(matrix10.T,matrix9)
print(matrix11)

[[1261163 1114271  668245]]


In [43]:
# task14
matrixA=np.random.randint(1,100,(3,3))
matrixb=np.random.randint(1,100,(3,1))
matrixx=np.linalg.solve(matrixA,matrixb)
print(matrixx)

[[ 2.6967976 ]
 [-1.61031333]
 [ 0.50055065]]


In [44]:
# task15
matrix1=np.random.randint(1,100,(5,5))

row_sums = np.sum(matrix1, axis=1)  
col_sums = np.sum(matrix1, axis=0) 
print(matrix1,row_sums,col_sums)

[[75 20 12 18 15]
 [18 67 89 91 57]
 [86 75 82 33 21]
 [10 61 73 81 70]
 [10 30 73 79 79]] [140 322 297 295 271] [199 253 329 302 242]
